# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_again_office',
                'doc_host': 'https://aloiswirth.github.io',
                'git_url': 'https://github.com/aloiswirth/nbdev_again_office',
                'lib_path': 'nbdev_again_office'},
  'syms': {'nbdev_again_office.core': {'nbdev_again_office.core.foo': ('core.html#foo', 'nbdev_again_office/core.py')}}}
